# Generated by Django 4.2.1 on 2023-06-02 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 20, 24, 58, 770691, tzinfo=datetime.timezone.utc)),
        ),
    ]
